// ============================================================
// PAYMENTS — سجل المدفوعات الموحّد
// ============================================================
// كل حركة نقدية مرتبطة بطرف (عميل أو مورد) تُسجَّل هنا، فيصير لكل قرش
// أثر يُراجَع: مين دفع، كام، إمتى، في أي خزينة، في أي وردية، ولأي فواتير.
// بدون هذا السجل كان تحصيل الدين يُنقص الرصيد ولا يترك خبراً عن المبلغ.

const PAYMENT_KINDS = {
  cust_collect: { label:'تحصيل من عميل',   dir:'in'  },
  sup_settle:   { label:'سداد لمورد',      dir:'out' },
  sale_collect: { label:'تحصيل فاتورة',    dir:'in'  },
};
const PAY_METHOD_LABELS = { cash:'نقدي', transfer:'تحويل بنكي', card:'بطاقة', check:'شيك' };

// يسجّل الدفعة ويحرّك الخزينة معاً. أي مسار مالي جديد يجب أن يمر من هنا.
async function recordPayment({ kind, partyType, partyId, partyName, amount, cashboxId,
                               method='cash', notes='', allocations=[], refId='', extra={} }){
  const dir = PAYMENT_KINDS[kind]?.dir || 'in';
  const cb  = (S.cashboxes||{})[cashboxId];
  const payId = uid();

  const data = {
    kind, dir,
    partyType, partyId, partyName: partyName||'',
    amount: +amount||0,
    method, notes,
    cashboxId:   cashboxId||'',
    cashboxName: cb?.name||'',
    // الفواتير التي أُطفئت بهذه الدفعة — تُظهر في كشف الحساب ما سُدِّد بالضبط
    allocations,
    refId,
    branchId:  CURRENT_USER?.branch||'',
    date:      new Date().toISOString().slice(0,10),
    createdAt: new Date().toISOString(),
    createdBy: CURRENT_USER?.id||'',
    createdByName: CURRENT_USER?.name||'',
    ...extra,
    ...shiftStamp(),
  };

  await dbSet('payments/'+payId, data);

  // حركة الخزينة: تحصيل يُودَع، وسداد يُصرَف
  if(cashboxId){
    await addCashboxEntry(
      cashboxId, +amount||0, dir==='in'?'deposit':'withdraw',
      `${PAYMENT_KINDS[kind]?.label||'دفعة'} — ${partyName||''}`.trim(),
      payId
    );
  }
  return payId;
}

// ============================================================
// إلغاء سداد / تحصيل اتسجّل بالغلط (صلاحية «إلغاء سداد» — المدير العام افتراضياً)
// ============================================================
// الدفعة مبتتمسحش: بتتعلّم «ملغاة» (مين وإمتى) وبيتعكس كل أثرها بالترتيب:
// الفواتير/أوامر الشراء اللي سدّدتها ترجع زي ما كانت، دين العميل يرجع بالمبلغ
// اللي اتشال منه فعلاً، الخزينة تاخد حركة عكسية في الوردية الحالية، ولو سداد
// مورد بيتشال المصروف التلقائي اللي اتسجّل معاه.
function canReversePayments(){ return !!CURRENT_USER && hasPerm(CURRENT_USER.role,'act-reverse-payment'); }

async function reversePayment(payId){
  const p=(S.payments||{})[payId];
  if(!p){ toast('الدفعة غير موجودة','error'); return; }
  if(p.reversed){ toast('الدفعة دي ملغاة قبل كده','warning'); return; }
  if(!canReversePayments()){ toast('ليس لديك صلاحية إلغاء السداد','error'); return; }

  const amount=+p.amount||0;
  const isIn = (p.dir||PAYMENT_KINDS[p.kind]?.dir)==='in';
  const ok=await confirm2(
    `هيتلغي ${PAYMENT_KINDS[p.kind]?.label||'الدفعة'} بمبلغ ${amount.toFixed(2)} — ${p.partyName||''}.\n`+
    (isIn ? 'المبلغ هيتخصم من الخزينة ويرجع ديناً على العميل.' : 'المبلغ هيرجع للخزينة ويرجع ديناً للمورد.'),
    'إلغاء سداد','↩️','إلغاء السداد','btn-danger');
  if(!ok) return;

  try{
    // 1) الفواتير وأوامر الشراء اللي الدفعة سدّدتها
    for(const a of (p.allocations||[])){
      const amt=+a.amount||0; if(!(amt>0)) continue;
      if(a.saleId && (S.sales||{})[a.saleId]){
        const s=S.sales[a.saleId];
        const bal=(+s.balance||0)+amt, paid=Math.max(0,(+s.amountPaid||0)-amt);
        await dbUpdate('sales/'+a.saleId,{ balance:bal, amountPaid:paid, status: bal<=0?'paid':(paid>0?'partial':'unpaid') });
      }
      if(a.poId && (S.purchaseOrders||{})[a.poId]){
        const po=S.purchaseOrders[a.poId];
        const bal=(+po.balance||0)+amt, paid=Math.max(0,(+po.amountPaid||0)-amt);
        await dbUpdate('purchaseOrders/'+a.poId,{ balance:bal, amountPaid:paid,
          payStatus: bal<=0?'completed':(paid>0?'partial':'unpaid'), updatedAt:new Date().toISOString() });
      }
    }
    // 2) دين العميل — الدفعات القديمة مفيهاش balReduced فبنرجّع المبلغ كله
    if(p.partyType==='customer' && p.partyId && (S.customers||{})[p.partyId]){
      const c=S.customers[p.partyId];
      const back = p.balReduced!==undefined ? (+p.balReduced||0) : amount;
      if(back>0) await dbUpdate('customers/'+p.partyId,{ balance:(+c.balance||0)+back });
    }
    // 3) الخزينة: حركة عكسية
    if(p.cashboxId && amount>0){
      await addCashboxEntry(p.cashboxId, amount, isIn?'withdraw':'deposit',
        `إلغاء ${PAYMENT_KINDS[p.kind]?.label||'دفعة'} — ${p.partyName||''}`.trim(), payId);
    }
    // 4) المصروف التلقائي لسداد المورد
    const exps=Object.entries(S.expenses||{}).filter(([,e])=>e.paymentId===payId && e.autoGenerated);
    for(const [eid] of exps) await dbRemove('expenses/'+eid);

    // 5) علامة الإلغاء على الدفعة نفسها
    await dbUpdate('payments/'+payId,{
      reversed:true, reversedAt:new Date().toISOString(),
      reversedBy:CURRENT_USER?.id||'', reversedByName:CURRENT_USER?.name||'',
      reversedShiftId:currentShiftId(),
    });
    toast('تم إلغاء السداد وعكس أثره ✅');
    if(_stmtCtx) renderStatement();
  }catch(e){ toast('خطأ: '+e.message,'error'); }
}

// ============================================================
// كشف الحساب — للعميل والمورد
// ============================================================
// يجمع كل ما يخصّ الطرف في حركة زمنية واحدة برصيد جارٍ، فيُقرأ الحساب
// كما يُقرأ دفتر: كل سطر يبيّن أثره على الرصيد وما آل إليه بعده.
// اصطلاح الإشارة: موجب = مستحق علينا أو له، سالب = سُدِّد.

let _stmtCtx = null;   // {type:'customer'|'supplier', id}

function openStatement(type, id){
  const party = type==='customer' ? (S.customers||{})[id] : (S.suppliers||{})[id];
  if(!party){ toast('لم يُعثر على بيانات الطرف','error'); return; }
  _stmtCtx = {type, id};
  document.getElementById('stmt-title').textContent =
    (type==='customer'?'كشف حساب عميل — ':'كشف حساب مورد — ') + (party.name||'');
  // نبدأ بكل الفترات حتى يظهر الرصيد الحقيقي لا جزءاً منه
  document.getElementById('stmt-from').value='';
  document.getElementById('stmt-to').value='';
  const payBtn=document.getElementById('stmt-pay-btn');
  payBtn.onclick=()=>{ closeModal('modal-statement'); openPayDebt(type==='customer'?'cust':'sup', id); };
  renderStatement();
  openModal('modal-statement');
}

function setStmtRange(r){
  const now=new Date(), iso=d=>d.toISOString().slice(0,10);
  let from='', to=iso(now);
  if(r==='month') from=iso(now).slice(0,7)+'-01';
  else if(r==='year') from=iso(now).slice(0,4)+'-01-01';
  else { from=''; to=''; }
  document.getElementById('stmt-from').value=from;
  document.getElementById('stmt-to').value=to;
  renderStatement();
}

// يبني كل حركات الطرف مرتّبة زمنياً
function buildStatementRows(type, id){
  const rows=[];
  const D=v=>(v||'').slice(0,10);

  // ما سُدِّد لاحقاً لكل فاتورة/أمر عبر سجل المدفوعات.
  // amountPaid على الفاتورة يتراكم مع كل تحصيل، فلو طرحناه كاملاً من قيمة
  // الفاتورة ثم طرحنا الدفعة مرة أخرى لحُسب المبلغ مرتين. لذا نستخرج
  // «المدفوع وقت البيع» = amountPaid − مجموع ما خُصص لها من دفعات لاحقة.
  const laterPaid = {};
  Object.values(S.payments||{}).forEach(p=>{
    if(p.reversed) return;   // الملغاة رجّعت amountPaid على الفاتورة بنفسها
    (p.allocations||[]).forEach(a=>{
      const key=a.saleId||a.poId;
      if(key) laterPaid[key]=(laterPaid[key]||0)+(+a.amount||0);
    });
  });

  if(type==='customer'){
    // المبيعات: تزيد ما على العميل بقيمة الآجل منها فقط
    Object.entries(S.sales||{})
      .filter(([,s])=>s.customerId===id||s.custId===id)
      .forEach(([sid,s])=>{
        const total=+s.total||0;
        const paidAtSale=Math.max(0,(+s.amountPaid||0)-(laterPaid[sid]||0));
        rows.push({
          at:s.createdAt||s.date||'', date:D(s.date||s.createdAt),
          kind:'sale', label:'فاتورة بيع',
          ref:s.invNumber||sid.slice(-6).toUpperCase(),
          total, paid:paidAtSale,
          effect:total-paidAtSale,              // الآجل وحده يدخل الرصيد
          note:(s.items||[]).length+' صنف',
        });
      });
    // التحصيلات
    Object.entries(S.payments||{})
      .filter(([,p])=>p.partyType==='customer'&&p.partyId===id)
      .forEach(([pid,p])=>rows.push({
        at:p.createdAt||'', date:D(p.date||p.createdAt),
        kind:'payment', label:'تحصيل نقدي', payId:pid, reversed:!!p.reversed,
        ref:pid.slice(-6).toUpperCase(),
        total:0, paid:+p.amount||0, effect:p.reversed?0:-(+p.amount||0),
        note:[PAY_METHOD_LABELS[p.method]||p.method, p.cashboxName].filter(Boolean).join(' — '),
      }));
    // مرتجعات المبيعات: تُنقص ما على العميل
    Object.entries(S.returns||{})
      .filter(([,r])=>r.type==='sale'&&(r.customerId===id||r.partyId===id))
      .forEach(([rid,r])=>rows.push({
        at:r.createdAt||r.date||'', date:D(r.date||r.createdAt),
        kind:'return', label:'مرتجع مبيعات',
        ref:rid.slice(-6).toUpperCase(),
        total:+r.total||0, paid:0, effect:-(+r.total||0),
        note:RETURN_REASONS[r.reason]||r.reason||'',
      }));
  } else {
    // المشتريات: تزيد ما على المحل للمورد بقيمة الآجل منها
    Object.entries(S.purchaseOrders||{})
      .filter(([,p])=>p.supplierId===id)
      .forEach(([pid,p])=>{
        const total=+p.total||0;
        const paidAtBuy=Math.max(0,(+p.amountPaid||0)-(laterPaid[pid]||0));
        rows.push({
          at:p.createdAt||p.date||'', date:D(p.date||p.createdAt),
          kind:'purchase', label:'أمر شراء',
          ref:p.poNumber||pid.slice(-6).toUpperCase(),
          total, paid:paidAtBuy, effect:total-paidAtBuy,
          note:(p.items||[]).length+' صنف',
        });
      });
    // السدادات للمورد
    Object.entries(S.payments||{})
      .filter(([,p])=>p.partyType==='supplier'&&p.partyId===id)
      .forEach(([pid,p])=>rows.push({
        at:p.createdAt||'', date:D(p.date||p.createdAt),
        kind:'payment', label:'سداد للمورد', payId:pid, reversed:!!p.reversed,
        ref:pid.slice(-6).toUpperCase(),
        total:0, paid:+p.amount||0, effect:p.reversed?0:-(+p.amount||0),
        note:[PAY_METHOD_LABELS[p.method]||p.method, p.cashboxName].filter(Boolean).join(' — '),
      }));
    // مرتجعات المشتريات: تُنقص ما علينا
    Object.entries(S.returns||{})
      .filter(([,r])=>r.type==='purchase'&&r.partyId===id)
      .forEach(([rid,r])=>rows.push({
        at:r.createdAt||r.date||'', date:D(r.date||r.createdAt),
        kind:'return', label:'مرتجع مشتريات',
        ref:rid.slice(-6).toUpperCase(),
        total:+r.total||0, paid:0, effect:-(+r.total||0),
        note:RETURN_REASONS[r.reason]||r.reason||'',
      }));
  }

  return rows.sort((a,b)=>(a.at||'').localeCompare(b.at||''));
}

function renderStatement(){
  if(!_stmtCtx) return;
  const {type,id}=_stmtCtx;
  const party = type==='customer' ? (S.customers||{})[id] : (S.suppliers||{})[id];
  if(!party) return;
  const currency=S.settings?.general?.currency||'EGP';
  const m=v=>Number(v||0).toFixed(2);
  const from=document.getElementById('stmt-from')?.value||'';
  const to  =document.getElementById('stmt-to')?.value||'';

  const all=buildStatementRows(type,id);
  // رصيد ما قبل الفترة يُعرض كسطر افتتاحي، فلا يبدو الكشف مبتوراً
  const opening=all.filter(r=>from&&r.date&&r.date<from).reduce((s,r)=>s+r.effect,0);
  const rows   =all.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));

  const canRev=canReversePayments();
  let bal=opening;
  const body=rows.map(r=>{
    bal+=r.effect;
    const color=r.effect>0?'var(--red)':'var(--green)';
    const sign =r.effect>0?'+':'';
    const badge={
      sale:'badge-info', purchase:'badge-purple', payment:'badge-success', return:'badge-warning'
    }[r.kind]||'badge-info';
    return `<tr>
      <td style="font-size:11px;color:var(--text2);white-space:nowrap;">${r.date||'—'}</td>
      <td><span class="badge ${r.reversed?'badge-danger':badge}" style="font-size:10px;">${r.label}${r.reversed?' — ملغى':''}</span></td>
      <td style="font-size:11px;font-weight:700;color:var(--accent);">${r.ref}</td>
      <td style="font-size:11px;color:var(--text2);">${r.note||'—'}</td>
      <td style="text-align:left;">${r.total?m(r.total):'—'}</td>
      <td style="text-align:left;color:var(--green);${r.reversed?'text-decoration:line-through;opacity:.6;':''}">${r.paid?m(r.paid):'—'}</td>
      <td style="text-align:left;font-weight:700;color:${color};">${sign}${m(r.effect)}</td>
      <td style="text-align:left;font-weight:800;">${m(bal)}</td>
      ${canRev?`<td style="text-align:center;">${r.kind==='payment'&&!r.reversed
        ?`<button class="btn btn-ghost btn-xs" onclick="reversePayment('${r.payId}')" title="إلغاء السداد وعكس أثره"><i class="fas fa-rotate-left"></i></button>`:''}</td>`:''}
    </tr>`;
  }).join('');

  // ملخص الفترة المعروضة
  const sum=k=>rows.filter(r=>r.kind===k&&!r.reversed).reduce((s,r)=>s+(k==='payment'?r.paid:r.total),0);
  const closing=bal;
  const label = type==='customer' ? 'مستحق على العميل' : 'مستحق للمورد';

  const info = type==='customer'
    ? [['الاسم',party.name],['الهاتف',party.phone||'—'],['النوع',PRICE_MODE_LABELS[party.custType]||'قطاعي'],
       ['البريد',party.email||'—'],['العنوان',party.addr||'—'],['الفرع',getBranchName(party.branchId)||'—'],
       ['تاريخ الإضافة',(party.createdAt||'').slice(0,10)||'—'],['كود العميل',id.slice(-6).toUpperCase()]]
    : [['الاسم',party.name],['الهاتف',party.phone||'—'],['المسؤول',party.contact||'—'],
       ['البريد',party.email||'—'],['العنوان',party.address||'—'],['الحالة',party.status==='active'?'نشط':'موقوف'],
       ['تاريخ الإضافة',(party.createdAt||'').slice(0,10)||'—'],['كود المورد',id.slice(-6).toUpperCase()]];

  const cards = type==='customer'
    ? [{l:'إجمالي المشتريات',v:m(sum('sale'))+' '+currency,c:'accent'},
       {l:'إجمالي المحصَّل',  v:m(sum('payment'))+' '+currency,c:'green'},
       {l:'إجمالي المرتجعات', v:m(sum('return'))+' '+currency,c:'yellow'},
       {l:label,             v:m(closing)+' '+currency,c:closing>0?'red':'green'}]
    : [{l:'إجمالي المشتريات منه',v:m(sum('purchase'))+' '+currency,c:'purple'},
       {l:'إجمالي المسدَّد',      v:m(sum('payment'))+' '+currency,c:'green'},
       {l:'مرتجعات المشتريات',   v:m(sum('return'))+' '+currency,c:'yellow'},
       {l:label,                v:m(closing)+' '+currency,c:closing>0?'red':'green'}];

  document.getElementById('stmt-body').innerHTML=`
    <!-- البيانات الشخصية -->
    <div class="card" style="margin-bottom:14px;">
      <div class="sec-title mb-3"><div class="sec-dot"></div>بيانات ${type==='customer'?'العميل':'المورد'}</div>
      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:9px;font-size:12.5px;">
        ${info.map(([k,v])=>`<div><span style="color:var(--text2);">${k}:</span> <strong>${v||'—'}</strong></div>`).join('')}
      </div>
      ${party.notes?`<div style="margin-top:10px;padding:8px 11px;background:var(--card2);border-radius:8px;font-size:12px;color:var(--text2);"><i class="fas fa-sticky-note"></i> ${party.notes}</div>`:''}
    </div>

    <!-- الملخص -->
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-bottom:14px;">
      ${cards.map(c=>`<div style="background:var(--card2);border-radius:10px;padding:12px;text-align:center;">
        <div style="font-size:15px;font-weight:900;color:var(--${c.c});">${c.v}</div>
        <div style="font-size:10.5px;color:var(--text2);margin-top:3px;">${c.l}</div>
      </div>`).join('')}
    </div>

    <!-- الحركة -->
    <div class="sec-title mb-3"><div class="sec-dot" style="background:var(--accent)"></div>حركة الحساب (${rows.length} حركة)</div>
    ${opening?`<div style="background:var(--card2);border-radius:8px;padding:9px 12px;font-size:12px;margin-bottom:9px;">
      رصيد ما قبل ${from}: <strong>${m(opening)} ${currency}</strong></div>`:''}
    ${rows.length?`<div class="tbl-wrap"><table>
      <thead><tr>
        <th>التاريخ</th><th>الحركة</th><th>المرجع</th><th>بيان</th>
        <th style="text-align:left;">القيمة</th><th style="text-align:left;">مدفوع</th>
        <th style="text-align:left;">الأثر</th><th style="text-align:left;">الرصيد</th>${canRev?'<th></th>':''}
      </tr></thead>
      <tbody>${body}</tbody>
      <tfoot><tr style="background:var(--card2);font-weight:800;">
        <td colspan="7" style="text-align:left;">الرصيد الختامي</td>
        <td style="text-align:left;color:${closing>0?'var(--red)':'var(--green)'};">${m(closing)} ${currency}</td>${canRev?'<td></td>':''}
      </tr></tfoot>
    </table></div>`
    :`<div style="text-align:center;padding:26px;color:var(--text2);background:var(--card2);border-radius:10px;">
        لا توجد حركات في هذه الفترة</div>`}

    <div style="margin-top:12px;font-size:11px;color:var(--text3);line-height:1.8;">
      الأثر الموجب يزيد ${type==='customer'?'ما على العميل':'ما على المحل للمورد'}، والسالب يُنقصه.
      المبيعات تدخل بقيمة الآجل منها فقط، لأن المدفوع نقداً لا يُنشئ ديناً.
    </div>`;
}

function exportStatementExcel(){
  if(!_stmtCtx){ return; }
  if(!xlsxReady()){ toast('مكتبة Excel غير محملة','error'); return; }
  const {type,id}=_stmtCtx;
  const party = type==='customer' ? (S.customers||{})[id] : (S.suppliers||{})[id];
  const currency=S.settings?.general?.currency||'EGP';
  const from=document.getElementById('stmt-from')?.value||'';
  const to  =document.getElementById('stmt-to')?.value||'';
  const all=buildStatementRows(type,id);
  const opening=all.filter(r=>from&&r.date&&r.date<from).reduce((s,r)=>s+r.effect,0);
  const rows=all.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));

  const wb=XLSX.utils.book_new();
  const head=[[`كشف حساب ${type==='customer'?'عميل':'مورد'}`],[''],
    ['الاسم',party.name||''],['الهاتف',party.phone||''],
    ['الفترة',(from||'البداية')+' إلى '+(to||'اليوم')],
    ['العملة',currency],[''],
    ['التاريخ','الحركة','المرجع','بيان','القيمة','مدفوع','الأثر','الرصيد']];
  let bal=opening;
  const data=rows.map(r=>{ bal+=r.effect;
    return [r.date,r.label+(r.reversed?' (ملغى)':''),r.ref,r.note,+r.total.toFixed(2),+r.paid.toFixed(2),
            +r.effect.toFixed(2),+bal.toFixed(2)]; });
  data.push(['','','','','','','الرصيد الختامي',+bal.toFixed(2)]);
  XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([...head,...data]),'كشف الحساب');
  XLSX.writeFile(wb,`كشف-حساب-${(party.name||'').replace(/\s/g,'_')}-${new Date().toISOString().slice(0,10)}.xlsx`);
  toast('✅ تم تصدير كشف الحساب');
}

